version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12-stretch
    steps:
      - run: echo "test"
  build:
    docker:
      - image: circleci/node:12-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker image build
          command: docker build -t mu-web .
      - run:
          name: Check docker run
          command: |
            docker run -d --name mu-web-container mu-web
            docker exec mu-web-container curl --retry 10 --retry-connrefused http://localhost/status
      - run:
          name: Save docker image
          command: docker image save mu-web > mu-web.tar

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires: 
            - test
