version: 2
jobs:
  unit_test:
    docker:
      - image: circleci/node:10
    steps:
      - run: echo "test"
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run: ./files/setup.sh
      - run: docker build -t mu-web .
      - run:
        command: |
          docker run -d mu-web --name mu-web-container
          docker exec /usr/sbin/nginx -g "daemon off;"
          docker exec mu-web-container curl --retry 10 --retry-connrefused http://localhost:8080

workflows:
  version: 2
  build:
    jobs:
      - unit_test
      - build:
        requires: unit_test
