version: 2
jobs:
  unit_test:
    docker:
      - image: node:12-stretch
    steps:
      - run: echo "test"
  build:
    docker:
      - image: node:12-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: ./files/setup.sh
      - run: docker build -t mu-web .
      - run:
          command: |
            docker run -d mu-web --name mu-web-container
            docker exec /usr/sbin/nginx -g "daemon off;"
            docker exec mu-web-container curl --retry 10 --retry-connrefused http://localhost:80

workflows:
  version: 2
  test_and_build:
    jobs:
      - unit_test
      - build:
          requires: 
            - unit_test
