version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12-stretch
    steps:
      - run: echo "test"
  build:
    docker:
      - image: circleci/node:12-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker image build
          command: docker build -t mu-web .
      - run:
          name: Check docker run
          command: |
            docker run -d --name mu-web-container mu-web
            docker exec mu-web-container curl --retry 10 --retry-connrefused http://localhost/status | grep 'Connection OK'
      - run:
          name: Save docker image
          command: docker image save mu-web > ./mu-web.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./mu-web.tar
  push:
    docker:
      - image: circleci/node:12-stretch
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Install pip
          command: |
            curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
            sudo python get-pip.py
            sudo apt install python-dev
      - run:
          name: Load docker image
          command: docker load -i ./mu-web.tar
      - run:
          name: Install aws-cli
          command: sudo pip install awscli --upgrade
      - run:
          name: Login ECR
          command: $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
      - run:
          name: Tag to latest
          command: docker tag mu-web:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:latest
      - run:
          name: Push image to ECR
          command: docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:latest
  deploy:
    docker:
      - image: circleci/node:12-stretch
    environment:
      DOCKER_IMAGE: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install ecs-cli
          command: |
            sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
      - run:
          name: Setup ecs-cli
          command: |
            ecs-cli configure --cluster ${ECS_CLUSTER} --default-launch-type EC2 --region ${AWS_DEFAULT_REGION} --config-name ecs-config
      - run:
          name: Stop Service
          command: |
            ecs-cli compose \
              --file .circleci/composition.yml \
              service down \
              --ecs-params .circleci/ecs-params.yml \
              --cluster-config ecs-config
      - run:
          name: Start Service
          command: |
            ecs-cli compose \
              --file .circleci/composition.yml \
              service up \
              --ecs-params .circleci/ecs-params.yml \
              --cluster-config ecs-config
              

workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - build:
          requires: 
            - test
      - push:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy:
