version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17.6-buster
    steps:
      - checkout
      - setup_remote_docker
          version: 19.03.14
      - run:
          name: Docker image build
          command: docker build -t mu-web .
      - run:
          name: Check docker run
          command: |
            docker run -d --name mu-web-container mu-web
            docker exec mu-web-container curl --retry 10 --retry-connrefused http://localhost/status | grep 'Connection OK'
      - run:
          name: Save docker image
          command: docker image save mu-web > ./mu-web.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./mu-web.tar
  push:
    docker:
      - image: circleci/node:14.17.6-buster
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load docker image
          command: docker load -i ./mu-web.tar
      - run:
          name: Install aws-cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Login ECR
          command: aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - run:
          name: Tag to latest
          command: docker tag mu-web:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:latest
      - run:
          name: Push image to ECR
          command: docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:latest
  deploy:
    docker:
      - image: circleci/node:14.17.6-buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Enviroment
          command:
            echo 'export DOCKER_IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:latest' >> $BASH_ENV
      - run:
          name: Install ecs-cli
          command: |
            sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
      - run:
          name: Setup ecs-cli
          command: |
            ecs-cli configure --cluster ${ECS_CLUSTER} --default-launch-type EC2 --region ${AWS_DEFAULT_REGION} --config-name ecs-config
      # 初回はService定義がないため、Stop Serviceをコメントアウトする必要がある。。。
      - run:
          name: Stop Service
          command: |
            ecs-cli compose \
              --file .circleci/composition.yml \
              --project-name mu-web \
              --ecs-params .circleci/ecs-params.yml \
              --cluster-config ecs-config \
              service stop
      - run:
          name: Start Service
          command: |
            ecs-cli compose \
              --file .circleci/composition.yml \
              --project-name mu-web \
              --ecs-params .circleci/ecs-params.yml \
              --cluster-config ecs-config \
              service up

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - push
          filters:
            branches:
              only: master
