version: 1
task_definition:
  services:
    mu-web-service:
      mem_limit: 524288000 # 500MB
      mem_reservation: 262144000 # 250MB
      secrets:
        - value_from: mu-developer-mail
          name: MAIL_ADDRESS
