name: pr-test-actions

on: pull_request

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t mu-web .
      - name: Test docker run
        run: |
          docker run -d --name mu-web-container mu-web
          sleep 10s
          docker exec mu-web-container curl --retry 10 --retry-connrefused http://localhost/status | grep 'Connection OK'
